stages:
  - security-test
  - deploy

sast:
  stage: security-test
include:
  - template: Security/SAST.gitlab-ci.yml

services:
  - docker:dind

deploy:
  stage: deploy
  tags:
    - deployment
  script:
    - sudo apt-get install -y python-pip
    - pip install docker-compose
    - docker-compose up -d --build
  environment:
    name: production
    url: https://money-manager.petar-cv.com
  only:
    - production
