version: '3.9'

services:
  keycloak-postgres:
    image: postgres:14.4
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_DB_DATABASE}
      POSTGRES_USER: ${KEYCLOAK_DB_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
    ports:
      - 5433:5432
    networks:
      - mm-network
  mm-postgres:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
    networks:
      - mm-network
  keycloak:
    image: jboss/keycloak:16.1.1
    volumes:
      - ./keycloak/keycloak-themes/custom:/opt/jboss/keycloak/themes/custom
      - ./keycloak/imports/realm-export.json:/tmp/realm-export.json
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_DB_DATABASE}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      # KEYCLOAK_LOGLEVEL: DEBUG
      # ROOT_LOGLEVEL: DEBUG
      KEYCLOAK_IMPORT: '/tmp/realm-export.json'
      PROXY_ADDRESS_FORWARDING: 'true'
    ports:
      - 8081:8080
      - 8443:8443
    depends_on:
      - keycloak-postgres
    networks:
      - mm-network
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - mm-network
  kafka:
    image: bitnami/kafka:3.2
    hostname: kafka
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - mm-network
  mm-api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3333:3333'
    depends_on:
      - kafka
      - mm-postgres
      - keycloak
    networks:
      - mm-network
  mm-frontend:
    build:
      context: .
      dockerfile: ./apps/money-manager/Dockerfile
    ports:
      - '4200:80'
    networks:
      - mm-network

networks:
  mm-network:
    driver: bridge

volumes:
  keycloak_postgres_data:
    driver: local
  postgres_data:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
