version: '3'

volumes:
  postgres_data:
    driver: local
  mm-postgres:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

services:
  keycloak-postgres:
    image: postgres:14.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${KEYCLOAK_POSTGRES_DB}
      POSTGRES_USER: ${KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${KEYCLOAK_POSTGRES_PASSWORD}
    ports:
      - 5433:5432
  mm-postgres:
    image: postgres:14.4
    volumes:
      - mm-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5434:5432
  keycloak:
    image: jboss/keycloak:16.1.1
    volumes:
      - ./keycloak/keycloak-themes/custom:/opt/jboss/keycloak/themes/custom
      - ./keycloak/imports:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      DB_VENDOR: POSTGRES
      DB_ADDR: ${KEYCLOAK_DB_ADDR}
      DB_DATABASE: ${KEYCLOAK_DB_DATABASE}
      DB_USER: ${KEYCLOAK_DB_USER}
      DB_SCHEMA: ${KEYCLOAK_DB_SCHEMA}
      DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      # KEYCLOAK_LOGLEVEL: DEBUG
      # ROOT_LOGLEVEL: DEBUG
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - keycloak-postgres
  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:3.2
    hostname: localhost
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  mm-api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '3333:3333'
    profiles:
      - production
    depends_on:
      - kafka
      - mm-postgres
      - keycloak
  mm-frontend:
    build:
      context: .
      dockerfile: ./apps/money-manager/Dockerfile
    ports:
      - '4200:4200'
    profiles:
      - production
    depends_on:
      - kafka
      - mm-postgres
      - keycloak
